# IF FOR SOME REASON THEY CHANGE THE DEFINITION OF THE CONSTANTS IN THE CPLEX MODULE, WE CAN CHANGE THEM HERE
# Constants for variables type
BINARY_VARIABLE = "B"
INTEGER_VARIABLE = "I"
CONTINUOUS_VARIABLE = "C"
# Constants for constraints sense"
GREATER_EQUAL = "G"
EQUAL = "E"
LESS_EQUAL = "L"
# Constants for CPLEX solution status
OPTIMAL_SOLUTION = 101
INFEASIBLE_SOLUTION = 103